- hosts: all
  become: yes
  tasks:
   - name: install pip
     apt:
       name: python3-pip
       state: present

   - name: install python pre-requisites
     pip:
       name:
         - openshift
         - pyyaml
         - kubernetes
       state: present

   - name: install curl
     apt:
       name: curl
       state: present

   - name: install git
     apt:
       name: git
       state: present

   - name: install wget
     apt:
       name: wget
       state: present

   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present

   - name: add Kubernetes apt-key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: add Kubernetes' APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

   - name: install kubelet
     apt:
       name: kubelet
       state: present
       update_cache: true

   - name: install kubeadm
     apt:
       name: kubeadm
       state: present

   - name: disable swap
     shell: |
       swapoff -a 
       sed -ri '/\sswap\s/s/^#?/#/' /etc/fstab

   - name: install Docker
     apt:
       name: docker.io
       state: present
       update_cache: true

   - name: ensure Docker service is enabled and started
     ansible.builtin.systemd:
       name: docker
       enabled: true
       state: started

   - name: download executables for Docker shim
     get_url: 
       url: https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.1/cri-dockerd-0.3.1.amd64.tgz 
       dest: $HOME/cri-dockerd-0.3.1.amd64.tgz
   
   - name: unpack and move executables for Docker shim in the corresponding directory
     shell: | 
       tar xvf cri-dockerd-0.3.1.amd64.tgz
       mv cri-dockerd/cri-dockerd /usr/local/bin/
     args:
       chdir: $HOME
       creates: /usr/local/bin/cri-dockerd

   - name: download systemd units for Docker shim 1
     get_url:
       url: https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.service
       dest: $HOME/cri-docker.service

   - name: download systemd units for Docker shim 2
     get_url:
       url: https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.socket
       dest: $HOME/cri-docker.socket
   
   - name: install systemd units for Docker shim 
     shell: |
       mv cri-docker.socket cri-docker.service /etc/systemd/system/
       sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service
     args:
       chdir: $HOME
       creates: /etc/systemd/system/cri-docker.socket

   - name: enable the service for Docker shim
     ansible.builtin.systemd:
       name: cri-docker.service
       enabled: true
       daemon_reload: true

   - name: enable and start the socket for Docker shim
     ansible.builtin.systemd:
       name: cri-docker.socket
       enabled: true
       state: started

   - name: ensure kubelet service is enabled
     ansible.builtin.systemd:
       name: kubelet
       enabled: true    

- hosts: master-node
  become: yes
  tasks:
   - name: install kubectl
     apt:
       name: kubectl
       state: present
       force: yes
