- hosts: masters
  become: yes
  tasks:
    - name: pull configuration images for master node
      shell: sudo kubeadm config images pull --cri-socket unix:///run/cri-dockerd.sock
    
    - name: initialize kubernetes cluster
      shell: |
        kubeadm init \
          --pod-network-cidr=192.168.0.0/16 \
          --cri-socket unix:///run/cri-dockerd.sock 

    - name: create .kube directory
      become: yes
      become_user: user_for_ansible
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes
        owner: user_for_ansible

    - name: install network plugin
      become: yes
      become_user: user_for_ansible
      shell: |
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/custom-resources.yaml
