- hosts: master-node
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['master-node'].join_command }} --cri-socket unix:///run/cri-dockerd.sock >> joined_to_cluster.txt"
      args:
        chdir: $HOME
        creates: joined_to_cluster.txt

- hosts: master-node
  tasks:
    - name: label node worloads
      shell: |
        kubectl label nodes worker-node-db workload=db
        kubectl label nodes worker-node-webapp workload=webapp
        kubectl label nodes docker-registry workload=docker-registry
        touch nodes_labeled.txt
      args:
        chdir: $HOME
        creates: nodes_labeled.txt 
