- hosts: master-node
  become: yes
  tasks:
    - name: pull configuration images for master node
      shell: sudo kubeadm config images pull --cri-socket unix:///run/cri-dockerd.sock >> images_pulled.txt
      args:
        chdir: $HOME
        creates: images_pulled.txt
    
    - name: initialize kubernetes cluster
      shell: |
        kubeadm init \
          --pod-network-cidr=192.168.0.0/16 \
          --cri-socket unix:///run/cri-dockerd.sock >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: user_for_ansible
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/user_for_ansible/.kube/config
        remote_src: yes
        owner: user_for_ansible

    - name: install network plugin 1
      become: yes
      become_user: user_for_ansible
      kubernetes.core.k8s:
        state: present
        src: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml

    - name: install network plugin 2
      become: yes
      become_user: user_for_ansible
      kubernetes.core.k8s:
        state: present
        src: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/custom-resources.yaml

    - name: download secret encryption plugin
      get_url:
        url: https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.19.5/kubeseal-0.19.5-linux-amd64.tar.gz
        dest: $HOME/kubeseal-0.19.5-linux-amd64.tar.gz

    - name: unpack and install secret encryption plugin
      shell: |
        tar -xvf kubeseal-0.19.5-linux-amd64.tar.gz
        mv kubeseal /usr/local/bin/kubeseal
      args:
        chdir: $HOME      
        creates: /usr/local/bin/kubeseal

    - name: create kubernetes controller pod
      become: yes
      become_user: user_for_ansible
      kubernetes.core.k8s:
        state: present
        src: https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.19.5/controller.yaml
